services:
  llm:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./models:/app/models
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
